### ISSUE TITLE
/locate lab command crashes client

### ISSUE THREAD

**Issue by InteJason** [elucent/eidolon#13]
**Describe the bug**
The mod works fine, but when this particular command is used, the world stops moving and you are forced to kill the client.

**To Reproduce**
1. Use Multimc to load the mod
2. Get in a world
3. Type /locate eidolon:lab
4. The world should stop loading
5. You are forced to kill the client

**Environment**
1.16.4, Single Player

**Crash Report**
There's no crash log since I have to kill the client myself.

**Comment by elucent** [comment]
I _think_ this should be fixed in the latest version. Turns out Minecraft's float RNG has some serious issues, causing structures that spawn with a low-ish chance to just not spawn at all. I've adapted the structure spawning code and it seems to have a much better distribution now, so I'm closing this - but please do reopen if the error persists.
