### ISSUE TITLE
Request: Slightly more forgiving goblet range

### ISSUE THREAD

**Issue by Viatos** [elucent/eidolon#23]
At present it's possible to build a drop shaft to kill things directly on the necessary block in front of the goblet, but this means you need to build some kind of tower and have your altar in the basement. This is certainly aesthetic, but there are other aesthetics, like the seaside lighthouse dedicated to the Old Ones where the _top_ is the place of ceremony, or great stepped pyramids, or mysterious floating islands laden with sullen villagers and abominable practices.

If the range a goblet could fill with blood from was extended to two blocks in all directions, you could use fences or the various "don't walk here" blocks in modded to easily position sacrifices with DIGNITY instead of them jumping onto the one-block-high altar table and wandering off. Extremely embarrassing when you're trying to look cool in front of the dark lord.

**Comment by elucent** [comment]
It was increased to two blocks in all directions in 0.2.3. If that's still not enough, maybe just change your approach?

 - Other than villagers, most passive mobs you'd want to sacrifice (cows, pigs, chickens, etc) can be easily oneshotted with a critical hit. You only need a stone axe or better. 

 - The cleaving axe will oneshot most passive mobs without a crit, as long as your attack meter is full.
 
 - You can weaken your sacrifices before sacrificing them. All you need is to deal the final blow near the altar. Keeping a pen of weakened animals or a prison of villagers feels befitting of a dark mage, no?
 
 - With a two block range, fences and other trapping mechanisms should have become viable. You can also use other modded means of trapping entities like an Ars Nouveau rune with a slowing spell.
 
Closing this because I think the mechanic is okay at the moment, it's definitely possible to perform aesthetically-pleasing sacrifices. If you've got any other more specific requests I'll take a look, but for now I'm closing this issue. There's a planned addition in the next major version which should make sacrifices much easier after a little progression as well.
