### ISSUE TITLE
0.2.2 "Rendering overlay" crash at startup.

### ISSUE THREAD

**Issue by sdaddy** [elucent/eidolon#6]
Client crash on startup.

https://gist.github.com/sdaddy/f64a08e107dca012173618ed7a55eae6

**Comment by elucent** [comment]
...Huh. My _guess_ is it's a mod conflict, but it's totally possible I'm doing something dumb. What modpack is this? Would be useful for testing locally.

**Comment by sdaddy** [comment]
It's a personal modpack. I zipped the [mods folder](https://drive.google.com/file/d/1fFIHLZd7ZsNWiC-tGY8D9hjhtaWrEvr8/view?usp=sharing) up if you would like to take a look. Using the latest Forge.

I don't believe it's your mod after further testing, but I can't pinpoint the exact one. I thought it might be [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib), but I've tried disabling it and the two mods that require it and still got errors. I'm stumped. I'd appreciate any help. Thank you.

**Comment by elucent** [comment]
Best practice is to [bisect](https://en.wikipedia.org/wiki/Bisection_(software_engineering)) your mod folder until you narrow it down. Remove half the mods, see which half has the error, rinse and repeat until you're left with the culprits. Definitely tedious, though. You'd expect this error if:

 - you were using a mod built for a version without the class mentioned by the error (TextureStitchEvent.Pre)
 - a mod was trying to load the class on the server (texture events are only present in the client)
 - your Forge was severely outdated
 
Judging by your log, though, none of these may apply - you're on the clientside, Forge is up-to-date, and none of your mods _that I've noticed_ were built for a previous version. That last part is a bit hard to skim, though. If there's any mods that you think might be messing with rendering or optimizations, or mods that might not be updated correctly, those might be good ones to try running without. Otherwise, bisecting is probably your best bet. It takes less time than you'd expect!

Anyways, just to confirm, does the crash occur without Eidolon installed? I'd like to know concretely whether or not this is a bug with the mod (although I'm happy to continue debugging with you in the comments) so I know whether or not I can close this issue.

**Comment by sdaddy** [comment]
Thanks so much for your time. Yes, I'm still getting the crash with Eidelon disabled. Each time it's another mod being labeled as the culprit. 

<details>
<summary>Neverending crashes</summary>
<p>

```
Time: 12/25/20 9:39 AM
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Buddycards (buddycards) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: net/minecraftforge/client/event/TextureStitchEvent$Pre

```
```

Time: 12/25/20 9:42 AM
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Supplementaries (supplementaries) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: net/minecraftforge/client/event/TextureStitchEvent$Pre

```
```

Time: 12/25/20 9:43 AM
Description: Rendering overlay

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file quark-common.toml of type COMMON for modid quark

```
```

Time: 12/25/20 9:52 AM
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: Farmer's Delight (farmersdelight) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: net/minecraftforge/client/event/TextureStitchEvent$Pre

```
</p>
</details>

Looks like it's back to the drawing board. You can close this issue. I'll update if and when I figure it out. Thanks again.

**Comment by sdaddy** [comment]
I tracked down [the culprit](https://github.com/lilypuree/Decorative-Winter/issues/4#issue-774783697) 

I still have no idea why it was throwing shade on yours and others mods. I also had to delete Quark's common.toml config file. Not sure if was corrupted during all these crashes or what. Oh well. Happy New Year's!
