### ISSUE TITLE
Soul Enchanter Compatability with Apotheosis

### ISSUE THREAD

**Issue by Chrisalisa** [elucent/eidolon#71]
Hello!
Apotheosis is a very widely used and customizable mod that improves vanilla enchanting mechanics by, for example, raising the level cap for a wide range of enchantments, allowing fortune to go above level 3(for example). I was wondering if it would be possible to at some point down the line implement some degree of compatibility between Eidolon and the enchantment adjustments added by Apotheosis so that levels of enchantment offered by Apotheosis could be achieved using the Soul Enchanter, instead of capping out at the vanilla levels for the enchantments.

**Comment by elucent** [comment]
I don't plan on adding this, specifically because Apotheosis carefully balances the higher level caps of enchantments with expensive bookshelves. As the soul enchanter doesn't use bookshelves, it wouldn't make sense to add bookshelf checks but _only_ when Apotheosis is installed and _only_ for higher level enchantments. And if I skipped the bookshelf check, the soul enchanter would become ludicrously powerful, bypassing the balancing mechanics of Apotheosis.

It's powerful enough as-is, so I think constraining it to a relatively weak-but-customizable enchanting method compared to the powerful-but-expensive enchanting table of Apotheosis is a fitting dichotomy.
