### ISSUE TITLE
[Suggestion] Soul Enchanter level requirement

### ISSUE THREAD

**Issue by Verquinox** [elucent/eidolon#73]
I imagined the soul enchanter would be a cool way to slowly power up your gear over time, adding a new enchant every few ingame days, until it's finally maxed out, but with a stack of xp bottles obtained from a cleric you can enchant all your gear to max level in a matter of minutes.

The main problem is that spending 3 levels when you're at level 3 is way easier than spending 3 levels when you're at level 30, since xp is exponential. So I can just add an enchant, splash a few bottles, add another enchant, splash a few more bottles, etc. (this also works if you have a mob farm)

I would recommend adding a level requirement of 10x the level you're spending, so to enchant something to Sharp I you would need 10 levels and spend 1, Sharp II would require 20 levels and spend 2, etc. This would make it so I can't take a stack of xp bottles and soul shards and instantly get all enchantments, but it would still be way more useful and convenient than a regular enchanting table.

**Comment by elucent** [comment]
Exponential XP was a mistake, I think. I don't want to add any mechanics that build off of one of vanilla's biggest flaws. There are some plans to balance the soul enchanter so it's more of a slow burn, but they will be tangential to the overall cost of enchanting - I don't like to make things pointlessly expensive as a balancing mechanism, since it only means more grinding rather than figuring out anything new.

Closing this with wontfix, but be aware that the Soul Enchanter has other balancing mechanics planned.
