### ISSUE TITLE
[Suggestion] Use stirring to advance stages in the Crucible

### ISSUE THREAD

**Issue by MarioSMB** [elucent/eidolon#90]
It's a well known fact that crucible recipes are tedious; they are highly dependent on timing, causing frequent losses in resources, especially when there are uncontrollable elements playing part, such as server lag.  
This is especially hard on new players who are learning the recipes, as it is unintuitive (there being no indication in the booklet of time sensitivity, one is still learning and will naturally be slower at throwing in the right ingredients). 

The suggestion here is, instead of relying solely on timing, perhaps stirring could act as a way to progress stages of a recipe. Some time-based elements could remain, such as requiring the entire process to be completed before a certain time limit (which could start once the water begins to boil, ending with the water fizzing out as it evaporates).  
Some of the recipes would need to be changed for this of course, but it would allow much more reliable and intuitive brewing with less risk of frustration from the unfair loss of materials.

**Comment by elucent** [comment]
I doubt this is a “well known fact”. I’m not changing it. Mods are allowed to make players deal with consequences, and learn to get better at avoiding them.

**Comment by MarioSMB** [comment]
With all due respect, that claim does not come lightly:  
https://github.com/elucent/eidolon/issues/47  
https://www.reddit.com/r/feedthebeast/comments/krsphb/eidolon_mod_crucible_not_working_properly/  
https://www.reddit.com/r/feedthebeast/comments/l11c7i/eidolon_mod_crucible_problem_shadow_gem/  
https://www.reddit.com/r/feedthebeast/comments/l0rmlv/underrated_magic_mods/gjviy8l/  
Along with multiple cases on the Eidolon Discord that I witnessed in just a short time visiting there. The response is always the same: do it quicker and hope you don't lose your items anyway.  

I understand the desire to add consequences, and that is perfectly acceptable, but please consider making it more intuitive; punishing players by deleting their items for not obeying fluctuating invisible timers is *not* a consequence or mechanic that will help players learn.

**Comment by elucent** [comment]
Not everything needs to be handed to the player, and getting confused doesn't mean a mechanic is bad. The crucible being somewhat confusing and lossy was very intentional, to force players to be careful when dealing with alchemical recipes. So I don't actually see anything wrong with people being confused by it - the point of the mechanic is for it to be something you need to figure out. And there are plenty of inexpensive recipes to practice on if you're especially worried.

Unfair aspects like lag making it very difficult to stir the right number of times are already addressed in development builds, and were reported in other issues. But I am not changing the mechanic overall when it is achieving exactly what it set out to do.

**Comment by MarioSMB** [comment]
It's more so frustration than it is confusion, but I appreciate the response and look forward to improvements to this mechanic in future releases of this otherwise amazing magic mod.  
Thank you for your time.
